# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0002_auto_20180928_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_name',
            field=models.CharField(max_length=50),
        ),
    ]
