# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-28 10:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snaps', '0003_auto_20180928_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['location']},
        ),
    ]
